apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: automation-pvc
  namespace: raster-qa
spec:
  storageClassName: azure-file
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi


